
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT FROM pg_tables
        WHERE tablename = 'bets'
    ) THEN
CREATE TABLE bets (
                      bet_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      user_id BIGINT NOT NULL,
                      event_id VARCHAR(255) NOT NULL,
                      event_marketid VARCHAR(255) NOT NULL,
                      eventwinnerid VARCHAR(255) NOT NULL,
                      bet_amount NUMERIC(12,2) NOT NULL
);
INSERT INTO bets (user_id, event_id, event_marketid, eventwinnerid, bet_amount)
VALUES
    (1, 'EVT123', '10', '5', 100.00),
    (2, 'EVT456', '20', '8', 250.50),
    (3, 'EVT789', '30', '12', 75.25),
    (1, 'EVT451', '10', '18', 150.50),
    (5, 'EVT989', '60', '12', 125.25);
END IF;
END
$$;